## PostgreSQL
  postgresql:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=brainweb
      - POSTGRES_PASSWORD=brainweb
      #- POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/data:/data
